services:
  backend:
    build: ./backend
    command: npm run dev
    volumes:
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
      - ./backend/.env:/app/.env
      - ./backend/uploads:/app/uploads
    ports:
      - '3002:3001'
    environment:
      - NODE_ENV=development
      - JWT_SECRET=jwt_secret_development_lanchego_key_123
      - FRONTEND_URL=http://localhost:4200
      - DATABASE_URL=postgres://postgres:postgres@host.docker.internal:5432/lanchego
    networks:
      - lanchego-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  lanchego-network:
    driver: bridge